tls/sni: refactored to reduce dependencies and improve Dispatcher.Shutdown()
darvaza-proxy/x pull request #10
Opened 2024-01-16 19:26 UTC by amery

2024-01-18 15:47 UTC, karasz requested changes

2024-01-18 15:47 UTC, karasz commented on tls/sni/dispatcher.go
> +// or the given context to timeout.
or the given context times out.

2024-01-18 19:04 UTC, amery commented
amended as requested

2024-01-23 14:52 UTC, karasz approved these changes
LGTM

2024-01-23 14:53 UTC, merged

2024-01-23 17:12 UTC, amery commented
`darvaza.org/x/tls@v0.1.2` tagged